---
title: "HW3-am6592"
author: "Adeena Moghni"
date: "2024-10-07"
output: github_document
---

```{r setup, include=FALSE}
library(tidyverse) #read csv
library(readxl) #read excel
library(haven) #read SAS
library(ggridges)
library(patchwork)

knitr::opts_chunk$set(
  fig.align = "center"
)
```

## Problem 2

```{r include=FALSE}
demo_df = 
  read.csv("data_imports/nhanes_covar.csv", na = c(".", "NA", ""),
          skip = 5,
          header = FALSE, 
          col.names = c("SEQN", "sex", "age", "BMI", "education")) %>% 
  janitor::clean_names() %>% 
  mutate(
    seqn = as.character(seqn),
    sex = as.factor(sex),
    age = as.integer(age),
    bmi = as.double(bmi),
    education = as.factor(education)
    )

mims_df = 
  read.csv("data_imports/nhanes_accel.csv", na = c(".", "NA", "")) %>% 
  janitor::clean_names() %>% 
  mutate(
    seqn = as.character(seqn)
  )

full_accel_df = left_join(mims_df, demo_df, by = "seqn") %>% 
  filter(age > 21) %>% 
  na.omit(full_accel_df) %>% 
  pivot_longer(
    min1:min1440,
    names_to = "minute", 
    values_to = "MIMS",
    names_prefix = "min") %>%  
  mutate(
    minute = as.factor(minute)
  )
```

```{r echo=FALSE, message = FALSE, warning = FALSE}
education_count =
  full_accel_df %>% 
  distinct(seqn, .keep_all = TRUE) %>% 
  na.omit(full_accel_df) %>% 
  mutate(sex = ifelse(sex == 1, "Male", "Female")) %>% 
  mutate(education = ifelse(education == 1, "Less than High School",
                            ifelse(education == 2, "High School Equivalent", "More than High School"))) %>% 
  group_by(sex, education) %>% 
  summarize(counts = n()) %>% 
  pivot_wider(
    names_from = "education", 
    values_from = "counts" )

knitr::kable(education_count)
```

```{r echo=FALSE, message = FALSE, warning = FALSE}
demo_plot = 
  demo_df %>% 
  filter(age > 21) %>%
  na.omit(demo_df) %>% 
  mutate(sex = ifelse(sex == 1, "Male", "Female")) %>% 
  mutate(education = ifelse(education == 1, "Less than High School",
                            ifelse(education == 2, "High School Equivalent", "More than High School")))

ggplot(demo_plot, aes(x = age, fill = education)) +
  geom_density(alpha = .4, adjust = .5, color = "blue") +
  facet_grid(~sex) +
  labs(title = "Distribution of Education Levels by Age",
       x = "Age", y = "density",
       fill = "Education Level") +
  theme_bw()
```

```{r echo=FALSE, message = FALSE, warning = FALSE}
activity_plot = 
  full_accel_df %>%
  group_by(seqn, age, sex, education) %>% 
  summarize(total_activity = sum(MIMS)) %>% 
  mutate(sex = ifelse(sex == 1, "Male", "Female")) %>% 
  mutate(education = ifelse(education == 1, "Less than High School",
                            ifelse(education == 2, "High School Equivalent", "More than High School")))
         

ggplot(activity_plot, aes(x = age, y = total_activity, color = education)) +
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_grid(~sex) +
  labs(title = "Total Daily Activity Levels vs. Age",
       x = "Age (years)", y = "Total Daily Activity (*MIMS)",
       color = "Education Level") +
  theme_bw()
```

```{r echo=FALSE, message = FALSE, warning = FALSE}
ggplot(activity_plot, aes(x = age, y = total_activity, color = sex)) +
  geom_point(alpha = .5) +
  geom_smooth(se = FALSE) +
  facet_grid(~education) +
  labs(title = "Total Daily Activity Levels vs. Age",
       x = "Age (years)", y = "Total Daily Activity (*MIMS)",
       color = "Education Level") +
  theme_bw()
```

## Problem 3
```{r include=FALSE}
jan2020_df = 
  read.csv("data_imports/citibike/Jan_2020_Citi.csv", na = c(".", "NA", "")) %>% 
  mutate("date" = "January 2020")

jan2024_df = 
  read.csv("data_imports/citibike/Jan_2024_Citi.csv", na = c(".", "NA", ""))%>% 
  mutate("date" = "January 2024")

july2020_df = 
  read.csv("data_imports/citibike/July_2020_Citi.csv", na = c(".", "NA", ""))%>% 
  mutate("date" = "July 2020")

july2024_df = 
  read.csv("data_imports/citibike/July_2024_Citi.csv", na = c(".", "NA", ""))%>% 
  mutate("date" = "July 2024")

combined_df = 
  bind_rows(jan2020_df, july2020_df, jan2024_df, july2024_df) %>% 
  rename("member_type" = "member_casual")
```

```{r echo=FALSE, message = FALSE, warning = FALSE}
ride_count =
  combined_df %>% 
  na.omit(combined_df) %>%
  group_by(date, member_type) %>%
  summarize(counts = n()) %>% 
  pivot_wider(
    names_from = "member_type", 
    values_from = "counts" )

knitr::kable(ride_count)
  
```

```{r echo=FALSE, message = FALSE, warning = FALSE}
july2024_rank =
  july2024_df %>% 
  na.omit(july_df) %>%
  group_by(start_station_name) %>%
  summarize(counts = n()) %>% 
  arrange(desc(counts)) %>% 
  slice(1:5)

knitr::kable(july2024_rank)

```

```{r}
median_plot = 
  combined_df %>% 
  na.omit(combined_df) %>%
  separate(date, into = c("month", "year")) %>% 
  group_by(weekdays, month, year) %>% 
  summarize(median_ride = median(duration))
  
ggplot(median_plot, aes(x = median_ride, y = weekdays, fill = year)) +
  geom_histogram(stat = "identity", position = "dodge") +
  facet_grid(~month) +
  labs(title = "Median Ride Time (minutes) vs. Days of the Week",
       x = "Media Ride Time (minutes)", y = "Weekdays") +
  theme_bw()
  
```


```{r}
df = 
  combined_df %>% 
  na.omit(combined_df) %>%
  separate(date, into = c("month", "year")) %>% 
  filter(year == 2024) %>% 
  group_by(month, member_type, rideable_type) %>% 
  reframe(duration)

ggplot(df, aes(x = month, y = duration, color = member_type)) +
  geom_boxplot() +
  facet_grid(~rideable_type) + 
  labs(title = "Distribution of Ride Times (minutes) vs. Month",
       x = "Month", y = "Ride Duration (minutes)") +
  theme_bw()
```
